### ISSUE TITLE
Include Rails route helpers

### ISSUE THREAD

**Issue by brendon** [scienceexchange/postmark_mailer#7]
Hi there, you might want to consider including rails route helpers in `PostmarkMailer::Base` since these will be commonly used for password resets etc...:

`include Rails.application.routes.url_helpers`

Depending on which rails version you support, that might need to be a conditional as I'm not sure it's always been the same include statement :)

**Comment by SeriouslyAwesome** [comment]
Hey @brendon, I think this makes sense on the surface, but in fact `ActionMailer::Base` doesn't even include these helpers. Typically you would explicitly include those helpers in the mailer subclasses where you need them, even without this gem.

Since I'm explicitly trying to keep this as similar in interface/functionality as `ActionMailer::Base`, I'm going to close this issue, but thank you for the feedback!

**Comment by brendon** [comment]
Ah I see, I guess I was getting confused by the helpers being available in the mailer views, and since PostmarkMailers have no views I assumed they'd be available there :) No worries :)
